package bcrypt

import (
	"errors"
	"strings"
	"testing"
)

// Frozen hashes were generated by the unmodified Go Authors' v0.57.0 package.
// Imported Supabase users retain these formats without password resets.
func TestLegacyPasswordHashes(t *testing.T) {
	vectors := []struct{ password, hash string }{
		{"LegacyFixture2026!", "$2a$04$HmAXhNHkynpu.kL70dH1R.JaJFPf4m7IwPNnl7yZME2AlekSey0km"},
		{"пароль\x00123", "$2a$04$7CERuhLu39pteuEo9SevjujQS9wzzlaGCjaHfwHmewm7DZCkeC5si"},
		{strings.Repeat("a", 72), "$2a$04$90j28c3uNKCb.BPoitxXoedd3qhQ7mB0EV07nJ7soU61fWeGDfQxG"},
	}
	for _, vector := range vectors {
		for _, version := range []string{"$2$", "$2a$", "$2b$", "$2y$"} {
			hash := version + strings.TrimPrefix(vector.hash, "$2a$")
			if err := CompareHashAndPassword([]byte(hash), []byte(vector.password)); err != nil {
				t.Fatalf("legacy %s hash rejected: %v", version, err)
			}
			if err := CompareHashAndPassword([]byte(hash), []byte("wrong-fixture-password")); !errors.Is(err, ErrMismatchedHashAndPassword) {
				t.Fatalf("incorrect password accepted for %s: %v", version, err)
			}
		}
	}
	// Historical comparison allows longer inputs even though generation rejects them.
	if err := CompareHashAndPassword([]byte(vectors[2].hash), []byte(strings.Repeat("a", 72)+"b")); err != nil {
		t.Fatalf("legacy long-input comparison changed: %v", err)
	}
	if _, err := GenerateFromPassword([]byte(strings.Repeat("a", 73)), MinCost); !errors.Is(err, ErrPasswordTooLong) {
		t.Fatalf("overlong generation changed: %v", err)
	}
	for _, malformed := range []string{"", "$2a$04$invalid", "$3a$04$HmAXhNHkynpu.kL70dH1R.JaJFPf4m7IwPNnl7yZME2AlekSey0km"} {
		if err := CompareHashAndPassword([]byte(malformed), []byte("LegacyFixture2026!")); err == nil {
			t.Fatal("malformed or unsupported hash accepted")
		}
	}
}
